Feat/jupiter
helium/wallet-app pull request #452
Opened 2023-09-08 22:49 UTC by bryzettler

2023-09-11 20:01 UTC, bryzettler commented
@matthewcarlreetz not that I know of. This was just to add Jupiter as the main means for the SwapsScreen. What needs to be done for location assertion?

2023-09-11 20:26 UTC, matthewcarlreetz commented
Nothing necessarily. I was just thinking we could allow them to pay the re-assert fee with IOT, MOBILE, or HNT. Right now it will only burn HNT (if needed).

> On Sep 11, 2023, at 3:01 PM, Bryan ***@***.***> wrote:
> 
> 
> @matthewcarlreetz <https://github.com/matthewcarlreetz> not that I know of. This was just to add Jupiter as the main means for the SwapsScreen. What needs to be done for location assertion?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/helium/wallet-app/pull/452#issuecomment-1714498178>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AANN4NM7QIODNLLFDQCT6X3XZ5UY5ANCNFSM6AAAAAA4Q7MX6A>.
> You are receiving this because you were mentioned.
>

2023-09-12 22:08 UTC, ChewingGlass requested changes

2023-09-12 22:08 UTC, ChewingGlass commented on src/features/swaps/SwapScreen.tsx
> +      !(routes?.outAmount && Number(routes?.outAmount) > 0) &&
Can this blowup with big numbers?

2023-09-12 22:08 UTC, ChewingGlass commented on src/features/swaps/SwapScreen.tsx
> +  useEffect(() => {
Do we want to useAsync here and catch/display errors?

2023-09-19 21:17 UTC, closed without merging